config/routes.rb
Rails.application.routes.draw do
  get    '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  get    '/logout',to: 'sessions#destroy'
  get    '/signup',to: 'users#new'

  get    '/dashboard', to: 'posts#index'
  post   'follow/user', to: 'users#follow_user', as: :follow_user
  delete   'unfollow/user/:following_id', to: 'users#unfollow_user', as: :unfollow_user
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: %i[index show create edit update destroy]
  resources :posts do 
    collection do 
      delete 'destroy_all_notify'
    end

    resources :likes, only: %i[create destroy]
  end
  resources :comments, only: %i[create destroy edit update]
  resources :messages
  resources :rooms

  root to: 'guest_pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/follower.rb
class Follower < ApplicationRecord
  belongs_to :users, optional: true
  validates_uniqueness_of :follower_id, scope: :following_id
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
  
  validates :user_id, uniqueness: { scope: :post_id }
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :notified_by, class_name: 'User'
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  include PublicActivity::Model
  tracked owner: Proc.new { |controller, model| controller.current_user ? controller.current_user : nil } 
  belongs_to :user
  has_many   :comments, dependent: :destroy
  has_many :notifications, as: :notificationable
  has_many :likes, dependent: :destroy
  has_one_attached :image

  validates :image, blob: { content_type: ['image/png', 'image/jpg', 'image/jpeg'], size_range: 1..(5.megabytes) }
end


app/models/room.rb
class Room < ApplicationRecord
  has_many :messages
  has_many :users, through: :messages
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }  
  has_secure_password
  attr_accessor :skip_validations_create, :skip_validations_update

  VALID_EMAIL_REGEX = /[a-z0-9]+@gmail.com/
  VALID_NICKNAME_REGEX = /[@#][A-Za-z0-9]/
  VALID_PHONE_REGEX = /\d{3}\-\d{3}\-\d{4}/
  PASSWORD_MIN_LENGTH = 6
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :followers, dependent: :destroy
  has_many :notifications, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_one_attached :image
  has_one_attached :background

  validates :name, presence: true,
                   length: { maximum: 30 }

  validates :nickname, presence: true,
                       uniqueness: true,
                       length: { maximum: 12 },
                       format: { with: VALID_NICKNAME_REGEX },
                       unless: :skip_validations_create

  validates :email, presence: true,
                    uniqueness: true,
                    length: { maximum: 100 }

  validates :password, presence: true,
                       length: { minimum: PASSWORD_MIN_LENGTH },
                       allow_nil: true

  validates :phone, presence: true,
                    allow_nil: true

  def total_followers
    Follower.where(follower_id: self.id).count
  end

  def total_following
    Follower.where(following_id: self.id).count
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :logged_in_user
  before_action :find_post, only: %i[create]

  def create
    @like = current_user.likes.find_or_initialize_by(post_id: @post.id)

    respond_to do |format|
      format.js{
        if @like.new_record?
          @like.save
          @success = true
        else
          @like.destroy
          @success = false
        end
                 
        render "posts/like.js.erb"
      }
    end
  end

  private 
  def find_post
    @post = Post.find(params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :logged_in_user
  before_action :load_activities, only: %i(index destroy show edit update)
  before_action :find_post, only: %i[destroy show edit update]
  def index
    # @posts = Post.all.order(created_at: :desc)
    @posts = []
    follows = Follower.where(follower_id: current_user.id)
    follows.each do |follow|
      @posts += Post.where(user_id: follow.following_id).order(created_at: :desc)
    end
    @posts += Post.where(user_id: current_user.id).order(created_at: :desc)
    @post = Post.new
  end
  
  def new
  end

  def create
    @post = current_user.posts.new(post_params)
    @post.save
    redirect_to request.referrer
  end

  def edit; end

  def show
    @comment = Comment.new
    @comments = @post.comments.order(created_at: :desc)
  end

  def destroy
    if @post.destroy
      flash.now[:success] = "Delete Success!"
      redirect_to request.referrer
    end
  end

  def destroy_all_notify
    @activity = PublicActivity::Activity.all
    @activity.destroy_all
    redirect_to request.referrer
  end

  def update
    if @post.update(post_params)
      redirect_to @post
    end
  end 

  private
  def find_post
    @post = Post.find(params[:id])
  end
  def post_params
    params.require(:post).permit(:user_id, :content, :image)
  end
  def load_activities
    @activities = PublicActivity::Activity.order('created_at DESC').limit(20)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/components_helper.rb
module ComponentsHelper
  def tw(classes)
    TailwindMerge::Merger.new.merge(classes)
  end

  PRIMARY_CLASSES = " bg-primary text-primary-foreground hover:bg-primary/80 "
  SECONDARY_CLASSES = " bg-secondary text-secondary-foreground hover:bg-secondary/80 "
  OUTLINE_CLASSES = "  border border-input bg-background hover:bg-accent hover:text-accent-foreground "
  GHOST_CLASSES = " hover:bg-accent hover:text-accent-foreground  "
  DESTRUCTIVE_CLASSES = " bg-destructive text-destructive-foreground hover:bg-destructive/90 "

  module Button
    PRIMARY = " bg-primary text-primary-foreground hover:bg-primary/80 "
    SECONDARY = " bg-secondary text-secondary-foreground hover:bg-secondary/80 "
    OUTLINE = "  border border-input bg-background hover:bg-accent hover:text-accent-foreground "
    GHOST = " hover:bg-accent hover:text-accent-foreground  "
    DESTRUCTIVE = " bg-destructive text-destructive-foreground hover:bg-destructive/90 "
  end

  module Alert
  end
end

app/helpers/guest_pages_helper.rb
module GuestPagesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def post_like_by_user? post_id
    current_user.likes.find_by(post_id: post_id).present?
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def logged_in?
    !current_user.nil?
  end

  def logged_in_user
    unless logged_in?
        flash[:danger] = "Please log in."
        redirect_to login_url
    end
  end

  def forget(user)
    cookies.delete(:user_id)
  end

  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.encrypted[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(:remember_digest, cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  def current_user?(user)
    user && user == current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tờ Quít Tơ</title>
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,600,700" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Source+Sans+Pro:ital,wght@0,200;0,300;0,400;0,600;0,700;0,900;1,700&display=swap" rel="stylesheet">
    <link rel="shortcut icon" type="image/x-icon" href="https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Twitter-logo.svg/2491px-Twitter-logo.svg.png">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,700;0,900;1,100&display=swap" rel="stylesheet">
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link href="https://fonts.googleapis.com/css2?family=Playpen+Sans:wght@200;300;600;700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Condensed:ital,wght@0,300;0,400;0,500;0,700;0,900;1,700&display=swap" rel="stylesheet">
    <%= favicon_link_tag 'TwitterX.svg' %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags 'application' %>

  </head>

  <body scrollbar="none">
    <%= yield %>
  </body>
</html>

app/views/public_activity/activities/_activity.html.erb
<% if activity.owner.present? %>
  <li style="display:flex;font-size:1rem;padding:10px 20px">
    <div>
      <% if activity.owner.image.present? %>
        <%= image_tag(activity.owner.image, style: 'width: 56px;height:56px;border-radius:50%') %>
      <% else %>
        <img style='width: 56px;height:56px;border-radius:50%' src="https://static.vecteezy.com/system/resources/thumbnails/009/292/244/small/default-avatar-icon-of-social-media-user-vector.jpg" />
      <% end %>
    </div>
    <div style="margin-left: 10px">
      <div>
        <% if activity.trackable %>
          <%= link_to post_path(activity.trackable), style: 'text-decoration:none;color:#fff' do %>
            <strong><%= activity.owner.name %></strong> add the Post
          <% end %>
        <% else %>
          <strong><%= activity.owner.name %></strong> was remove thanks card
        <% end %>
      </div>

      <div style="font-size:0.9rem;margin-top:4px">
        <i><%= time_ago_in_words(activity.created_at) %> ago</i>
      </div>
    </div>
  </li>
<% end %>

app/views/shared/_error_message.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains 
      <%= pluralize object.errors.count, 'error' %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="left">
      <div class="logo">
        <%= image_tag('logo.svg', width: '100px', style: 'object-fit:cover') %>
      </div>
      <ul class="left_list">
        <li>
          <i class='bx bx-home-circle'></i>
          <%= link_to "Home", dashboard_path, style: 'text-decoration:none;color:#fff' %>
        </li>
        <li>
          <i class='bx bx-toggle-right'></i>
          Explore
        </li>
        <li>
          <i class='bx bx-bell' style="position:relative"></i>
          <% if @activities.present? %>
            <div style="position:absolute;width: 20px;height: 20px;background-color: red;font-size: 0.9rem;display: flex;align-items: center;justify-content: center;border-radius: 50%;top: 230px;left: 20px;"><%= @activities.count %></div>
          <% end %>
          <label for="navbar" style="position:relative;outline:none;cursor:pointer;user-select:none">Notifications</label>

          <input type="checkbox" id="navbar" class="nv" hidden/>
          <ul class="render_notify" style='padding:20px 0'>
            <div style="padding: 0 20px;margin-bottom: 20px;display:flex;justify-content: space-between;align-items:center">
              <div>notification</div>
              <% if @activities.present? %>
                <%= link_to 'Delete All', destroy_all_notify_posts_path, method: :delete, data: { confirm: 'Are you sure?' }, style: 'color:#fff;font-size:1.2rem' %>
              <% end %>
            </div>
            <%= render @activities %>
          </ul>
        </li>
        <li>
          <i class='bx bx-message-rounded' ></i>
          <%= link_to "Message", rooms_path, style: 'text-decoration:none;color:#fff' %>
        </li>
        <li>
          <i class='bx bx-bookmarks' ></i>
          Bookmarks
        </li>
        <li>
          <i class='bx bx-user' ></i>
          <%= link_to "Profile", user_path(current_user), style: 'text-decoration:none;color:#fff' %>
        </li>
        <li>
          <i class='bx bx-user-circle'></i>
          <%= link_to "People", users_path, style: 'text-decoration:none;color:#fff' %>
        </li>
      </ul>

      <label for="ip-logout" style="display: flex;align-items: center;top: 130px;position: relative;padding: 10px;cursor:pointer;border-radius:14px">
        <div style="display: flex;align-items: center;">
          <% if current_user.image.present? %>
            <%= image_tag url_for(current_user.image), style: 'width: 40px;height:40px;border-radius:50%;object-fit:cover'%>
          <% else %>
            <img src="https://static.vecteezy.com/system/resources/thumbnails/009/292/244/small/default-avatar-icon-of-social-media-user-vector.jpg" width='40px' style='border-radius:50%'/>
          <% end %>
        </div>
        <div style="margin-left: 10px;">
          <p style="margin: 0"><%= current_user.name %></p>
          <% if current_user.nickname.present? %>
            <p style="margin: 0"><%= current_user.nickname %></p>
          <% end %>
        </div>
      </label>

      <input type="checkbox" hidden id="ip-logout" class="ip"/>

      <div class="h4_logout" style="position: absolute;border: 1px solid #ccc;border-radius: 14px;left: 54px;display:none">
        <%= link_to "Logout", logout_path %>
      </div>
    </div>