config/routes.rb
Rails.application.routes.draw do
  get    '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  get    '/logout',to: 'sessions#destroy'
  get    '/signup',to: 'users#new'

  get    '/dashboard', to: 'posts#index'
  post   'follow/user', to: 'users#follow_user', as: :follow_user
  delete   'unfollow/user/:following_id', to: 'users#unfollow_user', as: :unfollow_user
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: %i[index show create edit update destroy]
  resources :posts do 
    collection do 
      delete 'destroy_all_notify'
    end

    resources :likes, only: %i[create destroy]
  end
  resources :comments, only: %i[create destroy edit update]
  resources :messages
  resources :rooms

  root to: 'guest_pages#home'
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }  
  has_secure_password
  attr_accessor :skip_validations_create, :skip_validations_update

  VALID_EMAIL_REGEX = /[a-z0-9]+@gmail.com/
  VALID_NICKNAME_REGEX = /[@#][A-Za-z0-9]/
  VALID_PHONE_REGEX = /\d{3}\-\d{3}\-\d{4}/
  PASSWORD_MIN_LENGTH = 6
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :followers, dependent: :destroy
  has_many :notifications, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_one_attached :image
  has_one_attached :background

  validates :name, presence: true,
                   length: { maximum: 30 }

  validates :nickname, presence: true,
                       uniqueness: true,
                       length: { maximum: 12 },
                       format: { with: VALID_NICKNAME_REGEX },
                       unless: :skip_validations_create

  validates :email, presence: true,
                    uniqueness: true,
                    length: { maximum: 100 }

  validates :password, presence: true,
                       length: { minimum: PASSWORD_MIN_LENGTH },
                       allow_nil: true

  validates :phone, presence: true,
                    allow_nil: true

  def total_followers
    Follower.where(follower_id: self.id).count
  end

  def total_following
    Follower.where(following_id: self.id).count
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :logged_in_user, only: %i[index show follow_user unfollow_user edit update]
  before_action :load_activities, only: %i(index destroy show edit update)
  before_action :find_user, only: %i[show edit update index]
  def index
    @users = User.all

    following_ids = Follower.where(follower_id: current_user.id).map(&:following_id)
    following_ids << current_user.id
    @follower_suggestions = User.where.not(id: following_ids)
    @following = User.where(id: following_ids).where.not(id: current_user.id)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.skip_validations_create = true 
    if @user.save && verify_recaptcha(model: @user)
      redirect_to login_path
    else
      render :new
    end
  end

  def show 
    @posts = @user.posts.order(created_at: :desc)
    @check_follow = Follower.find_by(following_id: @user.id)
  end

  def follow_user
    follower_id = params[:follow_id]
    if Follower.create!(follower_id: current_user.id, following_id: follower_id)
      redirect_to request.referrer
    end
  end

  def unfollow_user
    @following_id = Follower.find_by(following_id: params[:following_id])
    @following_id.destroy
    redirect_to request.referrer
  end

  def edit; end
  
  def update
    if @user.update(user_params_update)
      flash.now[:success] = 'Profile updated'
      redirect_to @user
    else
      render :edit
    end
  end
  private 
  def user_params_update
    params.require(:user).permit(:name, :image, :background, :phone, :email, :nickname, :introduce, :password)
  end

  def user_params
    params.require(:user).permit(:name, :email, :phone, :nickname, :password, :password_digest)
  end

  def find_user
    @user = User.find_by(id: params[:id])
  end

  def load_activities
    @activities = PublicActivity::Activity.order('created_at DESC').limit(20)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_following.html.erb
<div style="display:flex;align-items: center;margin: 40px 0">
            <div style="display: flex;align-items: center;">
              <% if user.image.present? %>
                <%= image_tag(user.image, style: "width: 40px;height: 40px;border-radius: 50%;object-fit:cover" ) %>
              <% else %>
                <img src="https://static.vecteezy.com/system/resources/thumbnails/009/292/244/small/default-avatar-icon-of-social-media-user-vector.jpg", style="width: 40px;height: 40px;border-radius: 50%;" />
              <% end %>
            </div>

            <div style="margin-left: 18px;min-width:400px">
              <p style="margin: 0">
                <%= link_to user_path(user), style: 'color:#fff;text-decoration:none' do %>
                  <%= user.name %>
                <% end %>
              </p>
              <p style="margin: 0"><%= user.nickname %></p>
            </div>

            <div style="margin-left: 20px;">
              <%= form_tag follow_user_path, method: :post do %>
                <%= hidden_field_tag :follow_id, user.id %>
                <button style="cursor: pointer;border: none;width: 100px;height: 30px;border-radius: 10px;color: #fff;background-color: rgb(29, 155, 240);">Follow</button>
              <% end %>
            </div>
          </div>

app/views/users/_unfollowing.html.erb
<div style="display:flex;align-items: center;margin: 40px 0">
            <div style="display: flex;align-items: center;">
              <% if user.image.present? %>
                <%= image_tag(user.image, style: "width: 40px;height: 40px;border-radius: 50%;object-fit:cover" ) %>
              <% else %>
                <img src="https://static.vecteezy.com/system/resources/thumbnails/009/292/244/small/default-avatar-icon-of-social-media-user-vector.jpg", style="width: 40px;height: 40px;border-radius: 50%;" />
              <% end %>
            </div>

            <div style="margin-left: 18px;min-width:400px">
              <p style="margin: 0">
                <%= link_to user_path(user), style: 'color:#fff;text-decoration:none' do %>
                  <%= user.name %>
                <% end %>
              </p>
              <p style="margin: 0"><%= user.nickname %></p>
            </div>

            <div style="margin-left: 20px;">
              <%= link_to unfollow_user_path(user), method: :delete, style: 'text-decoration:none;color:#fff' do %>
                <button style="cursor: pointer;border: none;width: 100px;height: 30px;border-radius: 10px;color: #fff;background-color: rgb(29, 155, 240);">Unfollow</button>
              <% end %>
            </div>
          </div>

app/views/users/index.html.erb
<div class="main">
  <div class="w1400">
    <%= render 'shared/navbar' %>
    
    <div style="display:flex;flex-direction:column;width: 80%;position: relative;right: -400px;">
      <div class="friend">
        <h1>Following:</h1>
        <% if @following.present? %>
          <% @following.each do |follower| %>
            <%= render 'unfollowing', user: follower %>
          <% end %>
        <% else %>
          <div style="max-width: 400px;height: 100px;display: flex;align-items: center;justify-content: center;border: 1px solid #ccc;border-radius: 30px;color: #ccc;">
            <p>You are not following</p>
          </div>
        <% end %>
      </div>

      <div class="suggest">
        <h1>Suggest:</h1>
        <% if @follower_suggestions.present? %>
          <% @follower_suggestions.each do |user| %>
            <%= render 'following', user: user %>
          <% end %>
        <% else %>
          <div style="max-width: 400px;height: 100px;display: flex;align-items: center;justify-content: center;border: 1px solid #ccc;border-radius: 30px;color: #ccc;">
            <p>It's Over</p>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<%= form_with model: @user, class: 'form_login' do |f| %>
  <%= render 'sessions/above' %>

  <%= render 'shared/error_message', object: f.object %>
  <div class="sign_up" style="display:flex">
    <div class="inputGroup inputGroup1">
      <%= f.label :name, id: 'loginEmailLabel', for: 'loginEmail' %>
      <%= f.text_field :name, id: 'loginEmail', placeholder: 'Vinicius Jr'%>
      <%= f.label :email, id: 'loginEmailLabel', for: 'loginEmail' %>
      <%= f.text_field :email, id: 'loginEmail', placeholder: 'email@gmail.com'%>
      <%= f.label :phone, id: 'loginEmailLabel', for: 'loginEmail' %>
      <%= f.text_field :phone, id: 'loginEmail', placeholder: '079-456-8888'%>
    </div>
    <div class="inputGroup inputGroup2">
      <%= f.label :nickname, id: 'loginEmailLabel', for: 'loginEmail' %>
      <%= f.text_field :nickname, id: 'loginEmail',value: '@', placeholder: '@example'%>
      <%= f.label :password, id: 'loginPasswordLabel', for: 'loginPassword' %>
      <%= f.password_field :password, id: 'loginPassword'%>
      <%= f.label :password_confirmation, id: 'loginPasswordLabel', for: 'loginPassword' %>
      <%= f.password_field :password_confirmation, id: 'loginPassword'%>
      <label id="showPasswordToggle" for="showPasswordCheck">Show
        <input id="showPasswordCheck" type="checkbox" />
        <div class="indicator"></div>
      </label>
    </div>
  </div>
  <div style="display:flex;justify-content:center;margin:12px 0">
    <%= recaptcha_tags %>
  </div>
  <div class="inputGroup inputGroup3">
    <%= f.button 'Create', id: 'login' %>
    <%= link_to "Sign In", login_path, style: 'text-decoration:none;color:#fff', class: 'signup' %>
  </div>
<% end %>

<script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/1.20.3/TweenMax.min.js"></script>

<%# <%= javascript_pack_tag 'login' %> %>

app/views/users/show.html.erb
<div class="main">
  <div class="w1400">
    <%= render 'shared/navbar' %>

    <div class="right">
      <div class="right_center" style="background-image: url(<%= url_for(@user.background) if @user.background.present? %>);background-size:cover;height:245px;position:relative;background-position: center;">
        <div class="profile" style="position:absolute;display: flex;bottom: -90%;align-items: center;justify-content: space-between;width: 90%;">
          <div class="profile_left" style="display: flex;flex-direction: column;align-items: flex-start;flex: 6">
            <div class="profile_left-img" style="background-color: black;width: 190px;height: 190px;display: flex;align-items: center;justify-content: center;border-radius: 50%;">
              <% if @user.image.present? %>
                <%= image_tag url_for(@user.image), style: 'width: 180px;height:180px;border-radius: 50%;object-fit: cover;' %>
              <% else %>
                <img src="https://plusvalleyadventure.com/wp-content/uploads/2020/11/default-user-icon-8.jpg" style="width: 180px;height:180px;border-radius: 50%;object-fit: cover;"/>
              <% end %>
            </div>
            <div class="profile_left-name" style="margin: 10px 0;font-weight: 900;display:flex;align-items:center;width:100%">
              <div style="flex:1;display: flex;align-items: center;">
                <h3 style="margin: 0;font-weight: 900;font-size:2rem"><%= @user.name %></h3>
                <div style='display:flex;margin-left:20px;color:#fff;font-weight:700'>
                  <div>Post: <%= @posts.count %></div>
                  <div style="margin: 0 14px">Follower: <%= @user.total_followers %></div>
                  <div>Following: <%= @user.total_following %></div>
                </div>
              </div>
              <div>
              <% if !current_user?(@user) %>
                <% if @check_follow.present? %>
                    <div style="margin-left: 20px;">
                      <%= link_to unfollow_user_path(@user), method: :delete, style: 'text-decoration:none;color:#fff' do %>
                        <button style="cursor: pointer;border: none;width: 100px;height: 30px;border-radius: 10px;color: #fff;background-color: rgb(29, 155, 240);">Unfollow</button>
                      <% end %>
                    </div>
                <% else %>
                    <div style="margin-left: 20px;">
                      <%= form_tag follow_user_path, method: :post do %>
                        <%= hidden_field_tag :follow_id, @user.id %>
                        <button style="cursor: pointer;border: none;width: 100px;height: 30px;border-radius: 10px;color: #fff;background-color: rgb(29, 155, 240);">Follow</button>
                      <% end %>
                    </div>
                <% end %>
              <% end %>
              </div>
            </div>
            <div class="profile_left-nickname">
              <h5 style="margin: 16px 0;color: rgb(47, 51, 54);font-size:1.2rem"><%= @user.nickname %></h5>
            </div>
          </div>
          <% if current_user?(@user) %>
          <div class="profile_right" style="flex: 1">
            <label for="edit_profile" style="color: rgb(29, 155, 240);background: none;border: 1px solid rgb(29, 155, 240);/* padding: 10px 20px; */border-radius: 24px;cursor: pointer;display: flex;justify-content: center;padding: 10px;">Edit Profile</label>

            <input type="checkbox" id="edit_profile" hidden class="ed_profile"/>

            <label for="edit_profile" class="modal" style="position:fixed;top: 0;right: 0;bottom: 0;left: 0">
              <div class="mark" style="position:absolute;width:100%;height:100%;background-color: rgba(91, 112, 131, 0.4);display:flex;align-items:center;justify-content:center">
                <%= form_with model: @user do |f| %>
                  <div class="form_input">
                    <div class="bg" style="background-image: url(<%= url_for(current_user.background) if @user.background.present? %>);background-size:cover;background-position: center;">
                      <label style="cursor: pointer;font-size: 2rem;color: black;" for="background"><i class='bx bx-image-add' ></i></label>

                      <label for="img-inp" style="position:absolute;left: 35px;bottom: -82px;cursor: pointer;">
                        <div style="background-image:url(<%= url_for(current_user.image) if @user.background.present? %>);width: 200px;height: 200px;background-size: cover;background-position:center;border-radius: 50%;display: flex;justify-content: center;align-items: center;" style="width: 180px;height:180px;border-radius: 50%;font-size: 1.4rem;color: black;">
                          <i class='bx bx-image-add' style="color:black;font-size:1.4rem"></i>
                        </div>
                      </label>
                    </div>
                    <%= f.file_field :background, id: 'background', hidden: true %>
                    <%= f.file_field :image, class: "custom-file-input", id: "img-inp", hidden: true %>
                    <%= f.label :name %>
                    <%= f.text_field :name %>
                    <%= f.label :email %>
                    <%= f.text_field :email %>
                    <%= f.label :phone %>
                    <%= f.text_field :phone %>
                    <%= f.label :nickname %>
                    <%= f.text_field :nickname %>
                    <%= f.label :introduce %>
                    <%= f.text_field :introduce %>
                    <%= f.label :password %>
                    <%= f.password_field :password %>
                  </div>
                  <div class="upt-btn" style="display: flex;justify-content: center;margin-top: 20px;">
                    <%= f.submit 'Update', class: 'btn btn-primary' %>
                  </div>
                <% end %>
              </div>
            </label>
          </div>
        <% end %>
        </div>

        <div class="introduce" style="top: 222%;position: relative;z-index: -999">
          <p style="font-family:Comic Sans MS;"><i>"<%= @user.introduce %>"</i></p>
        </div>
      </div>

      <div class="show_post" style="margin-top: 240px;position:relative;z-index:-99">
          <% @posts.each do |post| %>
            <%= render 'posts/post', post: post %>
          <% end %>
        </div>
    </div>
  </div>
</div>
<%= javascript_import_module_tag  'like_ajax'%>