config/routes.rb
Rails.application.routes.draw do
  get    '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  get    '/logout',to: 'sessions#destroy'
  get    '/signup',to: 'users#new'

  get    '/dashboard', to: 'posts#index'
  post   'follow/user', to: 'users#follow_user', as: :follow_user
  delete   'unfollow/user/:following_id', to: 'users#unfollow_user', as: :unfollow_user
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: %i[index show create edit update destroy]
  resources :posts do 
    collection do 
      delete 'destroy_all_notify'
    end

    resources :likes, only: %i[create destroy]
  end
  resources :comments, only: %i[create destroy edit update]
  resources :messages
  resources :rooms

  root to: 'guest_pages#home'
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages
  has_many :users, through: :messages
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy]

  def index
    @rooms = Room.all
  end

  def show
    @rooms = Room.all
    render 'index'
  end

  def new
    @room = Room.new
  end

  def edit; end

  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_room
      @room = Room.find(params[:id])
    end

    def room_params
      params.require(:room).permit(:name)
    end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<%= form_with(model: room, local: true) do |form| %>
  <% if room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
        <% room.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group mb-3">
    <%= form.label "Add a new room", style: 'color:#fff' %>
    <%= form.text_field :name, class: 'form-control', placeholder: "Room name", style: 'border:1px solid #ccc' %>
  </div>

  <%= form.submit "Add", class: "btn btn-outline-primary btn-block" %>
<% end %>

app/views/rooms/edit.html.erb
<h1>Editing Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

app/views/rooms/index.html.erb
<div id="room-id" data-room-id="<%= @room.try(:id) %>"></div>
<div id="user-id" data-user-id="<%= current_user.id %>"></div>

<div class="container-fluid" style="background-color:#fff;padding:20px;border-radius:20px">
  <div class="row">
    <div class="col-3 rooms-sidebar">
      <div class="card no-outline">
        <div class="card-body">
          <small>Logged in as</small><br>
          <b><%= current_user.name %><br></b>
        </div>
      </div>
      <hr>
      <%= render 'form', room: Room.new %>
      <hr>
      <% @rooms.each do |room| %>
        <%= link_to room, class: 'room-link' do %>
          <% active_class = (@room == room) ? 'active' : '' %>
          <div class="card no-outline mb-2 room-card <%= active_class %>">
            <div class="card-body">
              <span class='name'><%= room.name %></span><br>
              <span class='member-count'>
                <small><%= room.users.uniq.count %> Members</small>
              </span>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
    <div class="col-9">
      <% if @room.present? %>
        <div class="chat-room">
          <nav class="navbar navbar-light">
            <span class="navbar-brand" href="#">
              <b><%= @room.name %></b>
            </span>
            <small><%= @room.users.uniq.count %> Members</small>
          </nav>
          <div id="messages">
            <% @room.messages.each do |message| %>
              <%= render 'messages/message', message: message %>
            <% end %>
          </div>
          <div class="chat-box">
            <%= render 'messages/form', message: Message.new, room: @room %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/rooms/new.html.erb
<h1>New Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Back', rooms_path %>

app/views/rooms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @room.name %>
</p>

<%= link_to 'Edit', edit_room_path(@room) %> |
<%= link_to 'Back', rooms_path %>